# Generated by Django 4.2.4 on 2023-08-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('0', 'Deshabilitado'), ('1', 'Habilitado')], max_length=1)),
            ],
        ),
    ]
