# Generated by Django 4.2.4 on 2023-08-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('0', 'Deshabilitado'), ('1', 'Habilitado')], max_length=1)),
            ],
        ),
    ]
