# Generated by Django 4.2.4 on 2023-08-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_matricula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'curso')},
        ),
    ]
